CC = g++
flg = -Wall -Wextra -g -Ofast -std=gnu++17 #-march=native

class_dir = class/
mainfile = test_net

h_files = randomGen network statMod tensor
cpp_files := $(h_files)

dir := ./$(class_dir)
h_all := $(join $(addsuffix $(class_dir), $(dir $(h_files))), $(h_files:=.h))
cpp_all := $(join $(addsuffix $(class_dir), $(dir $(cpp_files))), $(cpp_files:=.cpp))

output: $(mainfile).o $(cpp_all:.cpp=.o) $(h_all) $(cpp_all)
	$(CC) $(flg) $(mainfile).o $(cpp_all:.cpp=.o) -o $(mainfile)

$(mainfile).o: $(mainfile).cpp $(cpp_all)
	$(CC) $(flg) -c $(mainfile).cpp catch.o -o $(mainfile).o

$(dir)catch.o: $(dir)catch.hpp
	$(CC) $(flg) -c $(dir)catch.hpp -o $(dir)catch.o

$(dir)tensor.o: $(h_all) $(cpp_all)
	$(CC) $(flg) -c $(join $(dir), tensor.cpp) -o $(dir)tensor.o

$(dir)randomGen.o: $(h_all) $(cpp_all)
	$(CC) $(flg) -c $(join $(dir), randomGen.cpp) -o $(dir)randomGen.o

$(dir)network.o: $(h_all) $(cpp_all)
	$(CC) $(flg) -c $(join $(dir), network.cpp) -o $(dir)network.o

$(dir)statMod.o: $(h_all) $(cpp_all)
	$(CC) $(flg) -c $(join $(dir), statMod.cpp) -o $(dir)statMod.o

clean:
	rm *.o output
